title: Nguyen H. Phong # your name (or website title) here
logo: "/img/img_avatar.png?raw=true" # your photo (or logo) here
description: Researcher in Computer Science, especially Deep Learning. 
<br><br>

theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
