title: Nguyen H. Phong # your name (or website title) here
logo: "/img/photo4.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br>
  Data Scientist and Computer Science Researcher. PhD's degree in Informatics Engineering in July, 2023 from Coimbra University, Portugal (Since 1290). Member of Adaptive Computation at <a href="https://www.cisuc.uc.pt/en/people/nguyen-phong">CISUC</a>. Previously, MSc degree in
  Information Technology from <a href="https://www.siu.ac.th/">Shinawatra University, Thailand</a> and BSc in Physics from <a href="https://vnu.edu.vn/eng/">Vietnam Nationaly University, Hanoi</a>.
  <br>
  <br>
  Skilled in Deep Learning (action recognition, image classification, image segmentation, etc.)
  <br>
  <br>
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
